# Generated by Django 4.2.3 on 2023-08-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to='profile_images'),
        ),
    ]
