# Generated by Django 4.2.3 on 2023-08-07 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post_covers'),
            preserve_default=False,
        ),
    ]
