# Generated by Django 4.2.3 on 2023-08-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_profile_top_picks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_top_pick',
        ),
        migrations.RemoveField(
            model_name='post',
            name='top_pick_selected_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='top_picks',
        ),
    ]
