# Generated by Django 4.2.3 on 2023-08-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_bio_profile_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='iseoluwafalo@gmail.com', max_length=254),
        ),
    ]
