# Generated by Django 4.2.3 on 2023-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_editorpick1'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ManyToManyField(to='base.post')),
                ('profile', models.ManyToManyField(to='base.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='EditorPick1',
        ),
    ]
