# Generated by Django 4.2.3 on 2023-08-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_editorpick_delete_editorpick1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditorPick',
        ),
    ]
