# Generated by Django 4.2.3 on 2023-08-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_editorpick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorpick',
            old_name='post',
            new_name='posts',
        ),
    ]
