# Generated by Django 4.2.3 on 2023-08-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_editorpick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorpick',
            old_name='posts',
            new_name='post',
        ),
    ]
