# Generated by Django 4.2.3 on 2023-08-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_posts_editorpick_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_top_pick',
            field=models.BooleanField(default=False),
        ),
    ]
