# Generated by Django 4.2.3 on 2023-08-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_post_is_top_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='top_pick_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
