# Generated by Django 4.2.3 on 2023-08-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_post_top_pick_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='top_pick_timestamp',
            new_name='top_pick_selected_at',
        ),
    ]
