# Generated by Django 4.2.3 on 2023-08-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_top_pick_timestamp_post_top_pick_selected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='top_picks',
            field=models.ManyToManyField(blank=True, to='base.post'),
        ),
    ]
