# Generated by Django 4.2.3 on 2023-08-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_post_is_top_pick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='top_pick_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
