# Generated by Django 4.2.3 on 2023-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_post_top_pick_selected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_top_pick',
            field=models.BooleanField(default=False),
        ),
    ]
