# Generated by Django 4.2.3 on 2023-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_post_is_top_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='top_picks',
            field=models.ManyToManyField(blank=True, to='base.post'),
        ),
    ]
