# Generated by Django 4.2.3 on 2023-08-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_profile_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribers',
        ),
    ]
