# Generated by Django 4.2.3 on 2023-08-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_profile_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='EditorPick',
        ),
    ]
