# Generated by Django 4.2.3 on 2023-08-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
