# Generated by Django 4.2.3 on 2023-08-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_followerscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerscount',
            name='user',
            field=models.IntegerField(),
        ),
    ]
