# Generated by Django 4.2.5 on 2023-09-12 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0037_delete_followerscount_profile_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_recipients', models.ManyToManyField(related_name='custom_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
