# Generated by Django 4.2.5 on 2023-09-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_customnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomNotification',
        ),
    ]
