# Generated by Django 5.0 on 2023-12-18 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='Maximum word count exceeded.')]),
        ),
    ]
