# Generated by Django 5.0 on 2024-03-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_remove_series_series_posts_post_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(related_name='saved_by', to='base.post'),
        ),
    ]
