# Generated by Django 5.0 on 2024-03-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_rename_organizationprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='top_picks',
            field=models.ManyToManyField(blank=True, related_name='featured_in_organizations', to='base.post'),
        ),
    ]
