# Generated by Django 5.0 on 2024-03-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_post_organization_alter_organization_top_picks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='profile_img',
            field=models.ImageField(default='blank-org-profile.jpg', upload_to='profile_images'),
        ),
    ]
