# Generated by Django 5.0 on 2024-03-18 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_organization_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.organization'),
        ),
    ]
