
# Generated by Django 5.0 on 2024-03-28 14:06

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),  # Changed from ckeditor.fields.RichTextField()
        ),
    ]