# Generated by Django 5.0 on 2024-03-28 14:25

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),  # Changed from ckeditor_uploader.fields.RichTextUploadingField()
        ),
    ]
