# Generated by Django 5.0 on 2024-03-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='post_cover',
            field=models.ImageField(default='series-default.png', upload_to='series_covers'),
        ),
    ]
