# Generated by Django 5.0 on 2024-03-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_series_post_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='post_cover',
            new_name='series_cover',
        ),
    ]
