# Generated by Django 5.0 on 2024-04-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_rename_post_cover_series_series_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_cover',
            field=models.ImageField(default='no-image.png', upload_to='post_covers'),
        ),
    ]
