# Generated by Django 5.0 on 2024-05-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_post_post_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
