# Generated by Django 5.0 on 2024-07-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
