# Generated by Django 5.0 on 2024-07-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_notification_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
